application/posts/models.py
from datetime import datetime
from application import db


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime(), nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"

application/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

application/posts/views.py
from flask import render_template, flash, redirect, url_for, request, abort, Blueprint
from application.posts.forms import PostForm
from .models import Post
from application import db
from flask_login import current_user, login_required

posts = Blueprint('posts', __name__)


@posts.route("/post/create/", methods=['GET', 'POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash("Your post has been created!", 'success')
        return redirect(url_for('main.index'))

    return render_template("posts/create_post.html", title="Create Post", form=form, legend="Create Post")


@posts.route("/post/<int:post_id>/")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template("posts/read_post.html", title=post.title, post=post)


@posts.route("/post/<int:post_id>/update/", methods=["GET", "POST"])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash("Your post has been updated.", 'success')
        return redirect(url_for("posts.post", post_id=post.id))

    elif request.method == "GET":
        form.title.data = post.title
        form.content.data = post.content

    return render_template("posts/create_post.html", title='Update Post', form=form, legend="Update Post")


@posts.route("/post/<int:post_id>/delete/", methods=["POST"])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash("Your post has been delete!", "success")
    return redirect(url_for("main.index"))

application/users/views.py
from flask import render_template, flash, redirect, url_for, request, Blueprint
from application.users.forms import (
    SignUpForm,
    LogInForm,
    UpdateAccountForm,
    RequestResetForm,
    ResetPasswordForm
)
from .models import User
from application.posts.models import Post
from application import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from application.users.utils import send_reset_email, save_picture


users = Blueprint('users', __name__)


@users.route("/signup/", methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = SignUpForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash(f"Your account has been created! You are now able to log in.", 'success')
        return redirect(url_for('users.login'))
    return render_template("users/signup.html", title='SignUp', form=form)


@users.route("/login/", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LogInForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.index'))
        else:
            flash("Login unsuccessful. Please check email and password.", "danger")

    return render_template("users/login.html", title='LogIn', form=form)


@users.route("/logout/")
def logout():
    logout_user()
    return redirect(url_for('main.index'))


@users.route("/account/", methods=["GET", "POST"])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            current_user.image_file = save_picture(form.picture.data)
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash("Your account has been updated.", 'success')

        return redirect(url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename=f'images/profile_pictures/{current_user.image_file}')
    return render_template("users/account.html", title="Account", image_file=image_file, form=form)


@users.route("/user/<string:username>/")
def user_posts(username):
    user = User.query.filter_by(username=username).first_or_404()
    page = request.args.get('page', 1, type=int)
    posts = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=2)
    return render_template("users/user_posts.html", user=user, posts=posts)


@users.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash("An email has been sent with instructions to reset your password.", "info")
        return redirect(url_for("users.login"))

    return render_template("users/reset_request.html", title='Reset Password', form=form)


@users.route("/reset_password/<token>/", methods=["GET", "POST"])
def reset_token(token):

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    user = User.verify_reset_token(token)
    if user is None:
        flash("That is an invalid or expired token.", "warning")
        return redirect(url_for("users.reset_request"))
    form = ResetPasswordForm()

    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash(f"Your password has been updated! You are now able to log in.", 'success')
        return redirect(url_for('users.login'))

    return render_template("users/reset_token.html", title="Reset Password", form=form)

application/templates/about.html
{% extends 'layout.html' %}

{% block title %}
    Daily Blog - About Us
{% endblock title %}

{% block content %}
    <h1>About Page</h1>
{% endblock content %}

application/templates/account.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">

        <div class="media">

            <img class="rounded-circle account-img" src="{{ image_file }}">

            <div class="media-body">

                <h2 class="account-heading">{{ current_user.username }}</h2>

                <p class="text-secondary">{{ current_user.email }}</p>

            </div>

        </div>

        <form action="" method="post" novalidate enctype="multipart/form-data">

            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Account Info</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">

                    {{ form.picture.label() }}

                    {{ form.picture(class="form-control-file") }}

                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br/>
                        {% endfor %}
                    {% else %}

                    {% endif %}

                </div>

            </fieldset>

            <div class="form-group">

                {{ form.submit(class="btn btn-block btn-outline-info") }}

            </div>

        </form>

    </div>

{% endblock content %}

application/templates/create_post.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">

        <form action="" method="post" novalidate enctype="multipart/form-data">

            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">{{ legend }}</legend>

                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}

                    {% if form.title.errors %}
                        {{ form.title(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.title(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.content.label(class="form-control-label") }}

                    {% if form.content.errors %}
                        {{ form.content(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.content.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.content(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">

                {{ form.submit(class="btn btn-block btn-outline-info") }}

            </div>

        </form>

    </div>

{% endblock content %}

application/templates/index.html
{% extends 'layout.html' %}

{% block title %}
    Daily Blog - Dashboard
{% endblock title %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-imag" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" />

          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d %B, %Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}

        {% if page_num %}

            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('main.index', page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock content %}

application/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    {% block stylesheet %}
    {% endblock stylesheet %}

    {% if title %}
        <title>Daily Blog - {{ title }}</title>
    {% else %}
        <title>Daily Blog</title>
    {% endif %}
  </head>
  <body>
    <header class="site-header">

      <nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-steel fixed-top">

        <div class="container">

          <a class="navbar-brand" href="{{ url_for('main.index') }}">Daily Blog</a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarToggle">

            <div class="navbar-nav mr-auto">

              <a class="nar-item nav-link" href="/">Home</a>
              <a class="nav-item nav-link" href="/about">About</a>

            </div>

            <div class="navbar-nav">

              {% if current_user.is_authenticated %}

                <a class="nar-item nav-link" href="{{ url_for('posts.create_post') }}">Create Post</a>
                <a class="nar-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nar-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>

              {% else %}

                <a class="nar-item nav-link" href="{{ url_for('users.login') }}">Log In</a>
                <a class="nav-item nav-link" href="{{ url_for('users.signup') }}">Sign Up</a>

              {% endif %}

            </div>

          </div>

        </div>

      </nav>

    </header>

    <main role="main" class="container">

      <div class="row">

        <div class="col-md-8">

          {% with messages = get_flashed_messages(with_categories=true) %}

              {% if messages %}

                  {% for category, message in messages %}

                      <div class="alert alert-{{ category }}">
                          {{ message }}
                      </div>

                  {% endfor %}

              {% endif %}

          {% endwith %}

          {% block content %}
          {% endblock content %}

        </div>

        <div class="col-md-4">

          <div class="content-section">

            <h3>Our Sidebar</h3>

            <p class="text-muted">You can put any information here you'd like.</p>

            <ul>

              <li>Latest Posts</li>
              <li>Announcements</li>
              <li>Calendars</li>
              <li>etc</li>

            </ul>

          </div>

        </div>

      </div>

    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    {% block javascript %}
    {% endblock javascript %}
  </body>
</html>

application/templates/login.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">

        <form action="" method="post" novalidate>

            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Log In</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-check">

                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}

                </div>

            </fieldset>

            <div class="form-group">

                {{ form.submit(class="btn btn-block btn-outline-info") }}

                <small class="text-muted ml-2">

                <a href="{{url_for('users.reset_request')}}">Forgot Password?</a>

            </small>

            </div>

        </form>

    </div>

    <div class="border-top pt-3">

        <small class="text-muted">
            Need An Account? <a href="{{url_for('users.signup')}}" class="ml-2"> Sign Up Now </a>
        </small>

    </div>

{% endblock content %}

application/templates/post.html
{% extends 'layout.html' %}

{% block title %}
    Daily Blog - Dashboard
{% endblock title %}

{% block content %}
    <article class="media content-section">

          <img class="rounded-circle article-imag" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" />

          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d %B, %Y') }}</small>

              {% if post.author == current_user %}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">
                        Delete
                    </button>
                </div>
              {% else %}

              {% endif %}
            </div>
            <h2 class="article-title">{{ post.title }}</h2>
            <p class="article-content">{{ post.content }}</p>
          </div>

    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="post">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

application/templates/reset_request.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">

        <form action="" method="post" novalidate>

            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Reset Password</legend>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">

                {{ form.submit(class="btn btn-block btn-outline-info") }}

            </div>

        </form>

    </div>

{% endblock content %}

application/templates/signup.html
{% extends 'layout.html' %}

{% block content %}

    <div class="content-section">

        <form action="" method="post" novalidate>

            {{ form.hidden_tag() }}

            <fieldset class="form-group">

                <legend class="border-bottom mb-4">Sign Up Today</legend>

                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

            </fieldset>

            <div class="form-group">

                {{ form.submit(class="btn btn-block btn-outline-info") }}

            </div>

        </form>

    </div>

    <div class="border-top pt-3">

        <small class="text-muted">
            Already have an account? <a href="{{url_for('users.login')}}" class="ml-2"> Log In </a>
        </small>

    </div>

{% endblock content %}

application/templates/user_posts.html
{% extends 'layout.html' %}

{% block title %}
    Daily Blog - {{ user.username }}
{% endblock title %}

{% block content %}

    <h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>

    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-imag" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}" />

          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%d %B, %Y') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}

    {% for page_num in posts.iter_pages(left_edge=2, right_edge=2, left_current=2, right_current=3) %}

        {% if page_num %}

            {% if posts.page == page_num %}
                <a class="btn btn-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
            {% endif %}
        {% else %}
            ...
        {% endif %}

    {% endfor %}

{% endblock content %}